# Generated by Django 4.0.4 on 2022-05-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flashTitle', models.CharField(max_length=250)),
                ('flashUrl', models.URLField(max_length=250)),
            ],
        ),
    ]
