# Generated by Django 4.0.4 on 2022-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0002_flashnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goiLogoalt', models.CharField(max_length=250)),
                ('goiLogo', models.ImageField(null=True, upload_to='goiinit')),
                ('goiinitUrl', models.URLField(max_length=250)),
            ],
        ),
    ]
