# Generated by Django 4.0.4 on 2022-05-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0003_goi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goi',
            new_name='GoiInitiative',
        ),
    ]
