# Generated by Django 4.0.4 on 2022-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0005_studentworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(blank=True, max_length=250, null=True)),
                ('facultyProfile', models.ImageField(upload_to='facultyprofile')),
                ('facultyPhone', models.IntegerField(max_length=13)),
                ('facultyEmail', models.EmailField(max_length=250)),
                ('facultyQualification', models.CharField(max_length=250)),
                ('facultyDesignation', models.CharField(max_length=250)),
                ('facultyCv', models.FileField(upload_to='facultycv')),
                ('facultyPublication', models.URLField(max_length=250)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
