# Generated by Django 4.0.4 on 2022-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0008_alter_faculty_facultyphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('noticeFile', models.FileField(upload_to='noticeboard')),
                ('noticeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
