# Generated by Django 4.0.4 on 2022-05-27 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0010_post_postarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderTitle', models.CharField(max_length=255)),
                ('tenderFile', models.FileField(upload_to='tender')),
                ('tenderLastDate', models.DateTimeField(verbose_name=datetime.datetime)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostArchive',
        ),
    ]
