# Generated by Django 4.0.4 on 2022-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0011_tender_delete_post_delete_postarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadsTitle', models.CharField(max_length=255)),
                ('downloadsFile', models.FileField(upload_to='downloads')),
            ],
        ),
    ]
